package com.example.Sql_Rocks;


import jakarta.persistence.*;

@Entity
@Table(name="book")
public class Book {



    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY) //id parameter will be autogenerated in counting
    //user doesn't need to send it from postman
    private int id;

    private String name;

    private int pages;

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    //connect with the author class
    @ManyToOne
    @JoinColumn
    private Author author;


    public Book() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPages() {
        return pages;
    }

    public void setPages(int pages) {
        this.pages = pages;
    }
}
